#!/usr/bin/env python
import sys

def _startup():
    vtseq = lambda s: "\001\033%s\002" % s
    ansi = lambda s: vtseq("[%sm" % s)

    color = "32" if sys.version_info[0] >= 3 else "33"

    sys.ps1 = ansi("0;%s" % color) + ">>>" + ansi("0") + " "
    sys.ps2 = ansi("0;0") + "..." + ansi("0") + " "

_startup()
